export default {
  container: {
    position: 'relative',
    flex: 1,
    height: '100%',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'white',
  },
  row: {
    flex: 0,
    width: '100%',
    flexDirection: 'row',
    backgroundColor: '#f3f3f3',
    alignItems: 'center',
    height: 40,
    justifyContent: 'center',
  },
  text: {
    textAlign: 'center',
    height: '100%',
    flex: 1,
    textAlignVertical: 'center',
    color: 'black',
    fontSize: 14,
  },
  headingText: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  bottomBorder: {
    borderBottomColor: 'black',
    borderBottomWidth: 0.3,
  },
  flatList: {
    width: '100%',
    backgroundColor: 'aliceblue',
    marginBottom: 60,
  },
  filterBy: {
    flex: 0,
    borderColor: 'black',
    borderTopWidth: 0.5,
    borderBottomWidth: 0.5,
    width: '100%',
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  }, 
  dataView: {
    flex: 1,
    alignItems: 'center',
    width: '100%',
    justifyContent: 'center',
  },
  filterByText: {
    fontWeight: 'bold',
    fontSize: 16,
    color: 'black',
  },
  clientLead: {
    flex: 0,
    padding: 5,
    borderBottomColor: 'lightblue',
    borderBottomWidth: 10,
    marginTop: 20,
    alignSelf: 'flex-start',
    marginLeft: '10%',
    fontSize: 16,
    fontWeight: 'bold',
  },
  bottomNavItem: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomNav: {
    position: 'absolute',
    backgroundColor: 'white',
    bottom: 0,
    left: 0,
    right: 0,
    height: 60,
  },
  searchfield: {
    color: 'black',
    fontSize: 18,
  },
  borderBox: {
    height: 50,
    borderRadius: 5,
    borderWidth: 1,
    paddingLeft:5,
    paddingRight: 5,
    borderColor: 'grey',
  },
  buttonStyle: {
    marginTop: '10%',
    height: 50,
    marginLeft: 'auto',
    marginRight: 'auto',
    padding: 14,
  },
  buttonStyleText: {
    fontWeight: 'bold',
    textAlignVertical: 'center',
    color: 'black',
    fontSize: 16,
    textAlign: 'center',
  },
  modalContentWrapper: {
    backgroundColor: 'white',
    width: '84%',
    height: '50.15%',
    padding: '5%',
    marginRight: 'auto',
    marginLeft: 'auto',
  },
  modalcontainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    top: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.8)',
    width: '100%',
    height: '100%',
  },
};